# Default configuration for Network Monitor

# Network interface to capture packets from.
# Leave empty to let the program automatically select the first non-loopback interface.
# Example: "eth0", "enp3s0"
# interface: ""
interface: ""

# Network speed threshold in Mbps.
# If the overall network speed exceeds this value, a notification is sent.
threshold_mbps: 100.0

# Discord webhook URL to send notifications to.
# If empty, notifications are disabled.
# webhook_url: "https://discord.com/api/webhooks/.../..."
webhook_url: ""

# Time interval in seconds for checking the network speed and sending reports.
interval_seconds: 60

# Number of top IP addresses (by traffic volume) to include in the notification.
top_n: 5 