services:
  network-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: network-monitor
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml
    network_mode: "host" # Required for network monitoring
    cap_add:
      - NET_RAW
      - NET_ADMIN
    ports:
      - "9090:9090" # Prometheus metrics port
    environment:
      - NM_INTERFACE_NAME=${INTERFACE_NAME:-} # Can be overridden with environment variable 